apiVersion: v1
kind: PersistentVolume
metadata:
  name: rfqxpert-data-pv
  namespace: rfqxpert
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/rfqxpert-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rfqxpert-data-pvc
  namespace: rfqxpert
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
